name: Delete me later

on:
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: dev
    permissions:
      id-token: write
      contents: read
    steps:
      - run: |
          echo "OIDC Token: ${{ secrets.GITHUB_TOKEN }}"
      - uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: 'projects/${{ vars.PROJECT_NUMBER }}/locations/global/workloadIdentityPools/${{ vars.WIF_POOL }}/providers/${{ vars.WIF_PROVIDER }}'
          service_account: '${{ vars.SERVICE_ACCOUNT }}'
      - id: 'deploy'
        uses: 'google-github-actions/deploy-cloudrun@v2'
        with:
          service: 'hello-cloud-run'
          image: 'gcr.io/cloudrun/hello'
      - name: 'Use output'
        run: 'curl "${{ steps.deploy.outputs.url }}"'